### ISSUE TITLE
It's written in Java

### ISSUE THREAD

**Issue by connor4312** [Sponges/ProxyTester#1]

**Comment by Sponges** [comment]
stfu nodeboy

**Comment by connor4312** [comment]
:cry:

**Comment by Sponges** [comment]
:hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey:
